import React from "react";
import Link from "next/link";
import { getAuthSession } from "@/lib/auth";
import HomeSignInButton from "@/components/HomeSignInButton";
import HomeClientEffects from "@/components/HomeClientEffects";
import { 
  Sparkles, 
  Video, 
  BrainCircuit, 
  CreditCard, 
  BookOpen, 
  ChevronRight, 
  Users, 
  Trophy, 
  Coins 
} from "lucide-react";

export default async function Home() {
  const session = await getAuthSession();
  const isLoggedIn = !!session?.user;

  return (
    <div className="min-h-screen bg-white dark:bg-zinc-950 text-black dark:text-white transition-colors duration-300">
      
      {/* Decorative Grid Pattern Background */}
      <div className="absolute inset-0 bg-[linear-gradient(to_right,#80808012_1px,transparent_1px),linear-gradient(to_bottom,#80808012_1px,transparent_1px)] bg-[size:24px_24px] [mask-image:radial-gradient(ellipse_60%_50%_at_50%_0%,#000_70%,transparent_100%)] pointer-events-none" />

      {/* Hero Section */}
      <section className="relative pt-20 pb-12 md:pt-32 md:pb-20 max-w-7xl mx-auto px-6 sm:px-8 text-center flex flex-col items-center">
        
        {/* Animated Badge */}
        <div className="inline-flex items-center gap-2 px-4 py-2 rounded-full bg-violet-50 dark:bg-violet-950/40 border-2 border-black dark:border-white shadow-[2px_2px_0px_0px_rgba(0,0,0,1)] dark:shadow-[2px_2px_0px_0px_rgba(255,255,255,1)] mb-8 transform -rotate-1 hover:rotate-0 transition-transform">
          <Sparkles className="w-4 h-4 text-violet-600 dark:text-violet-400 fill-violet-600 dark:fill-violet-400" />
          <span className="text-xs font-black tracking-wide uppercase text-violet-900 dark:text-violet-200">
            AI-Powered Syllabus & Video Summaries
          </span>
        </div>

        {/* Hero Title */}
        <h1 className="text-4xl sm:text-6xl md:text-8xl font-black tracking-tight leading-none max-w-5xl">
          Learn Anything. <br />
          <span className="bg-gradient-to-r from-violet-600 via-indigo-600 to-cyan-600 bg-clip-text text-transparent dark:from-violet-400 dark:to-cyan-400">
            Generated by AI.
          </span> <br />
          Mastered by You.
        </h1>

        {/* Hero Subtitle */}
        <p className="mt-8 text-lg sm:text-xl md:text-2xl text-gray-600 dark:text-gray-400 max-w-3xl font-medium leading-relaxed">
          Minerva turns any topic into structured learning journeys. It generates custom units, fetches matching YouTube lectures, summarizes transcripts, and builds interactive quizzes.
        </p>

        {/* Call to Actions */}
        <div className="mt-10 flex flex-col sm:flex-row gap-6 justify-center items-center w-full sm:w-auto">
          {isLoggedIn ? (
            <div className="flex flex-col items-center gap-4">
              <div className="flex flex-col sm:flex-row gap-4">
                <Link
                  href="/create"
                  className="flex items-center justify-center gap-2 px-8 py-4 text-lg font-black text-black bg-yellow-400 dark:bg-yellow-500 border-2 border-black dark:border-white rounded-xl shadow-[4px_4px_0px_0px_rgba(0,0,0,1)] dark:shadow-[4px_4px_0px_0px_rgba(255,255,255,1)] hover:translate-x-[2px] hover:translate-y-[2px] hover:shadow-none active:translate-x-[4px] active:translate-y-[4px] active:shadow-none transition-all duration-150"
                >
                  Create New Course
                  <ChevronRight className="w-5 h-5" />
                </Link>
                <Link
                  href="/gallery"
                  className="flex items-center justify-center gap-2 px-8 py-4 text-lg font-black bg-white dark:bg-zinc-900 border-2 border-black dark:border-zinc-700 rounded-xl shadow-[4px_4px_0px_0px_rgba(0,0,0,1)] dark:shadow-[4px_4px_0px_0px_rgba(255,255,255,0.15)] hover:translate-x-[2px] hover:translate-y-[2px] hover:shadow-none active:translate-x-[4px] active:translate-y-[4px] active:shadow-none transition-all duration-150"
                >
                  Explore Course Gallery
                </Link>
              </div>
              <div className="flex items-center gap-2 px-4 py-1.5 bg-zinc-100 dark:bg-zinc-900 border border-zinc-200 dark:border-zinc-800 rounded-full text-xs font-bold text-gray-500 dark:text-gray-450 mt-2">
                <Coins className="w-4 h-4 text-yellow-500 fill-yellow-500/20" />
                <span>Logged in as <strong className="text-gray-800 dark:text-zinc-200">{session.user.name}</strong> • Remaining Credits: <strong className="text-gray-800 dark:text-zinc-200">{session.user.credits}</strong></span>
              </div>
            </div>
          ) : (
            <>
              <HomeSignInButton />
              <Link
                href="/gallery"
                className="flex items-center justify-center gap-2 px-8 py-4 text-lg font-black bg-white dark:bg-zinc-900 border-2 border-black dark:border-zinc-700 rounded-xl shadow-[4px_4px_0px_0px_rgba(0,0,0,1)] dark:shadow-[4px_4px_0px_0px_rgba(255,255,255,0.15)] hover:translate-x-[2px] hover:translate-y-[2px] hover:shadow-none active:translate-x-[4px] active:translate-y-[4px] active:shadow-none transition-all duration-150 w-full sm:w-auto"
              >
                Browse Gallery
              </Link>
            </>
          )}
        </div>
      </section>

      {/* Interactive Live Generator Section */}
      <section className="py-12 border-t border-b border-gray-100 dark:border-zinc-900 bg-gray-50/50 dark:bg-zinc-900/10">
        <HomeClientEffects />
      </section>

      {/* Feature Blocks Section */}
      <section className="py-20 max-w-7xl mx-auto px-6 sm:px-8">
        <div className="text-center mb-16">
          <h2 className="text-3xl sm:text-5xl font-black tracking-tight">
            Engineered For Modern Learning
          </h2>
          <p className="text-gray-600 dark:text-gray-400 mt-4 max-w-xl mx-auto text-base">
            Everything you need to turn vague curiosities into structured, validated expertise.
          </p>
        </div>

        {/* Feature Grid */}
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-8">
          
          {/* Card 1: AI Syllabus Planner */}
          <div className="p-6 bg-white dark:bg-zinc-900 border-2 border-black dark:border-zinc-700 rounded-2xl shadow-[4px_4px_0px_0px_rgba(0,0,0,1)] dark:shadow-[4px_4px_0px_0px_rgba(255,255,255,0.1)] hover:-translate-y-1 hover:shadow-[6px_6px_0px_0px_rgba(0,0,0,1)] dark:hover:shadow-[6px_6px_0px_0px_rgba(255,255,255,0.15)] transition-all duration-300">
            <div className="w-12 h-12 bg-violet-100 dark:bg-violet-950/40 rounded-xl flex items-center justify-center border border-violet-200 dark:border-violet-800 text-violet-600 dark:text-violet-400 mb-6">
              <Sparkles className="w-6 h-6 fill-current" />
            </div>
            <h3 className="text-xl font-bold mb-2">AI Syllabus Planner</h3>
            <p className="text-gray-600 dark:text-gray-400 text-sm leading-relaxed">
              Enter any keyword or concept. Our AI drafts detailed, chronological structures customized to your skill level.
            </p>
          </div>

          {/* Card 2: Smart Video Summaries */}
          <div className="p-6 bg-white dark:bg-zinc-900 border-2 border-black dark:border-zinc-700 rounded-2xl shadow-[4px_4px_0px_0px_rgba(0,0,0,1)] dark:shadow-[4px_4px_0px_0px_rgba(255,255,255,0.1)] hover:-translate-y-1 hover:shadow-[6px_6px_0px_0px_rgba(0,0,0,1)] dark:hover:shadow-[6px_6px_0px_0px_rgba(255,255,255,0.15)] transition-all duration-300">
            <div className="w-12 h-12 bg-blue-100 dark:bg-blue-950/40 rounded-xl flex items-center justify-center border border-blue-200 dark:border-blue-800 text-blue-600 dark:text-blue-400 mb-6">
              <Video className="w-6 h-6" />
            </div>
            <h3 className="text-xl font-bold mb-2">Curation & Summaries</h3>
            <p className="text-gray-600 dark:text-gray-400 text-sm leading-relaxed">
              We locate the most relevant YouTube lessons, extract transcripts, and generate clear, easy-to-read notes.
            </p>
          </div>

          {/* Card 3: Interactive Quizzes */}
          <div className="p-6 bg-white dark:bg-zinc-900 border-2 border-black dark:border-zinc-700 rounded-2xl shadow-[4px_4px_0px_0px_rgba(0,0,0,1)] dark:shadow-[4px_4px_0px_0px_rgba(255,255,255,0.1)] hover:-translate-y-1 hover:shadow-[6px_6px_0px_0px_rgba(0,0,0,1)] dark:hover:shadow-[6px_6px_0px_0px_rgba(255,255,255,0.15)] transition-all duration-300">
            <div className="w-12 h-12 bg-emerald-100 dark:bg-emerald-950/40 rounded-xl flex items-center justify-center border border-emerald-200 dark:border-emerald-800 text-emerald-600 dark:text-emerald-400 mb-6">
              <BrainCircuit className="w-6 h-6" />
            </div>
            <h3 className="text-xl font-bold mb-2">Adaptive Quizzes</h3>
            <p className="text-gray-600 dark:text-gray-400 text-sm leading-relaxed">
              Test your understanding instantly with AI-generated multiple-choice questions custom tailored to the units.
            </p>
          </div>

          {/* Card 4: Stripe Pro Plan */}
          <div className="p-6 bg-white dark:bg-zinc-900 border-2 border-black dark:border-zinc-700 rounded-2xl shadow-[4px_4px_0px_0px_rgba(0,0,0,1)] dark:shadow-[4px_4px_0px_0px_rgba(255,255,255,0.1)] hover:-translate-y-1 hover:shadow-[6px_6px_0px_0px_rgba(0,0,0,1)] dark:hover:shadow-[6px_6px_0px_0px_rgba(255,255,255,0.15)] transition-all duration-300">
            <div className="w-12 h-12 bg-amber-100 dark:bg-amber-950/40 rounded-xl flex items-center justify-center border border-amber-200 dark:border-amber-800 text-amber-600 dark:text-amber-400 mb-6">
              <CreditCard className="w-6 h-6" />
            </div>
            <h3 className="text-xl font-bold mb-2">Stripe Integration</h3>
            <p className="text-gray-600 dark:text-gray-400 text-sm leading-relaxed">
              Upgrade seamlessly to the Pro subscription model via Stripe for unlimited generations and premium support.
            </p>
          </div>

        </div>
      </section>

      {/* How it Works / Stats section */}
      <section className="py-20 bg-zinc-50 dark:bg-zinc-900/30 border-t border-b border-gray-200 dark:border-zinc-900">
        <div className="max-w-7xl mx-auto px-6 sm:px-8">
          <div className="grid grid-cols-1 lg:grid-cols-3 gap-12 items-center">
            
            <div className="lg:col-span-1">
              <h2 className="text-3xl sm:text-4xl font-black tracking-tight leading-tight">
                Designed for Autodidacts & Students
              </h2>
              <p className="text-gray-600 dark:text-gray-400 mt-4 text-sm sm:text-base leading-relaxed">
                Minerva skips the fluff of traditional courses, bringing you laser-focused video timestamps and validation checks. Start your course and level up today.
              </p>
              <div className="mt-8 space-y-4">
                <div className="flex items-center gap-3">
                  <div className="w-6 h-6 bg-yellow-400 border border-black rounded-full flex items-center justify-center font-bold text-xs text-black">
                    ✓
                  </div>
                  <span className="font-bold text-sm">Interactive custom progress bars</span>
                </div>
                <div className="flex items-center gap-3">
                  <div className="w-6 h-6 bg-yellow-400 border border-black rounded-full flex items-center justify-center font-bold text-xs text-black">
                    ✓
                  </div>
                  <span className="font-bold text-sm">Credits system with simple topups</span>
                </div>
                <div className="flex items-center gap-3">
                  <div className="w-6 h-6 bg-yellow-400 border border-black rounded-full flex items-center justify-center font-bold text-xs text-black">
                    ✓
                  </div>
                  <span className="font-bold text-sm">Robust community course gallery</span>
                </div>
              </div>
            </div>

            {/* Quick stats visualization */}
            <div className="lg:col-span-2 grid grid-cols-1 sm:grid-cols-3 gap-6">
              
              <div className="p-8 bg-white dark:bg-zinc-900 border-2 border-black dark:border-zinc-800 rounded-2xl text-center shadow-[4px_4px_0px_0px_rgba(0,0,0,1)] dark:shadow-none">
                <Users className="w-8 h-8 mx-auto text-violet-600 mb-4" />
                <h4 className="text-3xl font-black">2,400+</h4>
                <p className="text-gray-500 dark:text-gray-400 text-xs font-bold uppercase tracking-wider mt-2">Active Students</p>
              </div>

              <div className="p-8 bg-white dark:bg-zinc-900 border-2 border-black dark:border-zinc-800 rounded-2xl text-center shadow-[4px_4px_0px_0px_rgba(0,0,0,1)] dark:shadow-none">
                <BookOpen className="w-8 h-8 mx-auto text-blue-600 mb-4" />
                <h4 className="text-3xl font-black">15,000+</h4>
                <p className="text-gray-500 dark:text-gray-400 text-xs font-bold uppercase tracking-wider mt-2">Courses Generated</p>
              </div>

              <div className="p-8 bg-white dark:bg-zinc-900 border-2 border-black dark:border-zinc-800 rounded-2xl text-center shadow-[4px_4px_0px_0px_rgba(0,0,0,1)] dark:shadow-none">
                <Trophy className="w-8 h-8 mx-auto text-emerald-600 mb-4" />
                <h4 className="text-3xl font-black">94.8%</h4>
                <p className="text-gray-500 dark:text-gray-400 text-xs font-bold uppercase tracking-wider mt-2">Completion Rate</p>
              </div>

            </div>

          </div>
        </div>
      </section>

      {/* CTA Footer Wrapper */}
      <section className="py-20 text-center max-w-4xl mx-auto px-6 sm:px-8 relative">
        <h2 className="text-3xl sm:text-5xl font-black tracking-tight">
          Ready to Build Your Custom Syllabus?
        </h2>
        <p className="text-gray-650 dark:text-gray-400 mt-6 text-lg max-w-xl mx-auto font-medium">
          Start generating custom units and test your skills with dynamic quizzes now.
        </p>
        <div className="mt-10 flex justify-center">
          {isLoggedIn ? (
            <Link
              href="/create"
              className="flex items-center justify-center gap-2 px-8 py-4 text-lg font-black text-black bg-yellow-400 dark:bg-yellow-500 border-2 border-black dark:border-white rounded-xl shadow-[4px_4px_0px_0px_rgba(0,0,0,1)] dark:shadow-[4px_4px_0px_0px_rgba(255,255,255,1)] hover:translate-x-[2px] hover:translate-y-[2px] hover:shadow-none active:translate-x-[4px] active:translate-y-[4px] active:shadow-none transition-all duration-150"
            >
              Start Generating Course
            </Link>
          ) : (
            <HomeSignInButton />
          )}
        </div>
      </section>

      {/* Simple Footer */}
      <footer className="py-8 border-t border-gray-200 dark:border-zinc-900 max-w-7xl mx-auto px-6 sm:px-8 text-center text-xs text-gray-500 dark:text-gray-400 font-bold">
        <p>© {new Date().getFullYear()} Minerva. Powered by AI and community passion. All rights reserved.</p>
      </footer>

    </div>
  );
}
